base/app/config/urls.py
# django imports
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('user.urls', namespace='users')),
    path('api/v1/', include('commerce.urls', namespace='commerce')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/app/user/urls.py
from django.urls import path

from user import views


app_name = 'user'

urlpatterns = [
    path('token/', views.CreateTokenView.as_view(), name='token'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup')

]

base/app/user/views.py
"""user views"""

# Django RF imports
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.settings import api_settings
from rest_framework import generics, authentication, permissions


# Django imports
from django.contrib.auth import authenticate

from django.contrib.auth import login
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import redirect

# Exceptions
from django.db.utils import IntegrityError

# models and serializers
from user.serializers import AuthTokenSerializer
from user.serializers import UserSerializer

def login_view(request):
    """login view"""
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('/admin/')
        else:
            return render(
                request,
                'users/login.html',
                {'error': 'invalid username or password'}
            )
    return render(request, 'users/login.html')


@login_required
def logout_view(request):
    """logout view"""
    logout(request)
    return redirect("users:login")


def signup_view(request):
    """sign up view"""
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']
        if password != password_confirmation:
            return render(
                request,
                'users/signup.html',
                {'error': 'password confirmation does not match'}
            )
        try:
            get_user_model().objects.create_user(
                email=email,
                password=password
            )
        except IntegrityError:
            return render(
                request,
                'users/signup.html',
                {'error': 'email already in use'}
            )

        return redirect("users:login")
    return render(request, 'users/signup.html')


class CreateUserView(generics.CreateAPIView):
    """Create a new user in the system"""
    serializer_class = UserSerializer


class CreateTokenView(ObtainAuthToken):
    """Create a new token for a user"""
    serializer_class = AuthTokenSerializer
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES


class ManageUserView(generics.RetrieveUpdateAPIView):
    """Manage the authenticated user"""
    serializer_class = UserSerializer
    authentication_classes = (authentication.TokenAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get_object(self):
        """Retrieve and return authenticated user"""

        return self.request.user

base/app/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/e-commerce.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

base/app/templates/users/login.html
{% extends "users/base.html" %}
{% block head_content %}
<title>Sign in omni-dev-test</title>
{% endblock  %}
{% block container %}
    {% if error %}
    <p class="alert alert-danger">{{  error }}</p>
    
    {% endif %}
    
    <form action="{% url "users:login" %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input  type="email" placeholder="Email" name="username" class="form-control">
        </div>
        
        <div class="form-group">
            <input  type="password" placeholder="Password" name="password" class="form-control">
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in</button>
        <p class="login-wrapper-footer-text">Don't have an account? <a href="{% url "users:signup" %}" class="text-reset">Register here</a></p>
    
    </form>
{% endblock  %}

base/app/templates/users/signup.html
{% extends "users/base.html" %}
{% block head_content %}
<title>Sign up omni-dev-test</title>
{% endblock  %}
{% block container %}
{% if error %}
    <p class="alert alert-danger">{{  error }}</p>
    
{% endif %}

<form action="{% url "users:signup" %}" method="post">
    {% csrf_token %}
    <div class="form-group">
            <input  type="email" placeholder="Email" name="email" class="form-control" required="true">
    </div>
    <div class="form-group">
            <input  type="password" placeholder="Password" name="password" class="form-control" required="true">
    </div>
    <div class="form-group">
            <input  type="password" placeholder="Password Confirmation" name="password_confirmation" class="form-control" required="true">
    </div>
    <button class="btn btn-primary btn-block mt-5" type="submit">Register</button>
    <div class="text-center w-100">
        <p class="text-muted font-weight-bold">Already Registered? <a href="{% url "users:login" %}" class="text-primary ml-2">Login</a></p>
    </div>
</form>

{% endblock  %}